### ISSUE TITLE
Fix typos in README.md

### ISSUE THREAD

**Issue by kichloo** [LoginRadius/csharp-password-hash#1]
I can fix the typos and update the README. md. So, kindly assign me this issue.

**Comment by anilswm** [comment]
Hey @kichloo Thanks for contributing to LoginRadius Open Source.  As part of hacktoberfest, LoginRadius is also giving free swags and goodies to its contributors. Please check out our [Hacktoberfest Page](https://www.loginradius.com/engineering/page/hacktoberfest2020) and fill the form mentioned there to become eligible for free swags. :)

**Comment by kichloo** [comment]
@anilswm Thanks for the information. And I wanted to know whether I should start working now or after the labelling?

**Comment by anilswm** [comment]
@kichloo You can start work. thank you
