### ISSUE TITLE
EncryptPassword needs to be renamed

### ISSUE THREAD

**Issue by fedelippo** [LoginRadius/csharp-password-hash#12]
`Hashing.EncryptPassword` actually performs a hashing of it. There's a substantial [difference between encryption and hashing](https://stackoverflow.com/questions/4948322/fundamental-difference-between-hashing-and-encryption-algorithms).
Therefore `EncryptPassword` should be renamed `HashPassword`

**Comment by anilswm** [comment]
Thanks @fedelippo 

Thanks for contributing to LoginRadius Open Source.  As part of hacktoberfest, LoginRadius is also giving free swags and goodies to its contributors. Please check out our [Hacktoberfest Page](https://www.loginradius.com/engineering/page/hacktoberfest2020) and fill the form mentioned there to become eligible for free swags. :)
