### ISSUE TITLE
Create a method to get a valid configuration for any hash

### ISSUE THREAD

**Issue by anilswm** [LoginRadius/csharp-password-hash#18]
Create a method to get the possible hashing algo for an existing hash

```
(algo, encoding) GetPossibleConfig(password, salt, saltedPasswordFormat, inputhash)
{
//create a hash of the password using all possible combination of supported algo
//match the hash with inputhash
//return the config if it generates the same hash
}
```
Logic should be dynamic so it can work for new algo also.

**Comment by BamButz** [comment]
Hello i would like to take on this. :)

**Comment by priyanka1111** [comment]
@anilswm i would like to work on this. Can u please explain a bit.

**Comment by priyanka1111** [comment]
@anilswm salt in this is be available in the function ?

**Comment by anilswm** [comment]
@priyanka1111 Yes salt will be available in the function. I have updated the description. 

Thanks for contributing to LoginRadius Open Source.  As part of hacktoberfest, LoginRadius is also giving free swags and goodies to its contributors. Please check out our [Hacktoberfest Page](https://www.loginradius.com/engineering/page/hacktoberfest2020) and fill the form mentioned there to become eligible for free swags. :)

**Comment by priyanka1111** [comment]
@anilswm Hi, it is done.  Please check PR #25 .
