### ISSUE TITLE
HMAC_SHA1 and HMAC_SHA256 is not supporting all encoding types

### ISSUE THREAD

**Issue by anilswm** [LoginRadius/csharp-password-hash#19]
https://github.com/LoginRadius/csharp-password-hash/blob/master/csharp-password-hash/csharp-password-hash/Hashing.cs

Method ToHMAC_SHA1 and ToHMAC_SHA256 are not supporting all encoding like others.

**Comment by Fyers** [comment]
You can assign this to me. I would generally refactor all the repeations into a base function that uses https://docs.microsoft.com/en-US/dotnet/api/system.security.cryptography.hashalgorithm.computehash?view=netcore-3.1 which all hashes inherit form. and return the encoded result from there.

That would also solve the issue that new encodings must be added everywhere with the exact same code in 10 different places.
