### ISSUE TITLE
Add a separate test case to match the GetHash method's output with few existing hash values, without using CheckPassword method

### ISSUE THREAD

**Issue by anilswm** [LoginRadius/csharp-password-hash#2]

**Comment by fedelippo** [comment]
Can I have this assigned please?

**Comment by ashish8947** [comment]
Yeah sure @fedelippo, I will add you as assignee. LoginRadius is also giving swags to people who will be contributing, so please make sure to read our blog and submit your info to get free goodies.

https://www.loginradius.com/engineering/page/hacktoberfest2020
