### ISSUE TITLE
MD5 and HMAC-SHA256 are not disposed

### ISSUE THREAD

**Issue by fedelippo** [LoginRadius/csharp-password-hash#23]
Crypto objects implements IDisposable therefore need to be disposed of. 
MD5 and HMAC-SHA256 lack the "using" statement.

Ref: https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.md5?redirectedfrom=MSDN&view=netcore-3.1

**Comment by anilswm** [comment]
Thanks @fedelippo
