### ISSUE TITLE
HashingAlgo.MD5 only allows ASCII

### ISSUE THREAD

**Issue by Fyers** [LoginRadius/csharp-password-hash#29]
Unlike all other Hash functions MD5 uses `ASCII.GetBytes()`, instead of `UTF8.GetBytes()`

If this is fixes, the call to `ToHashAlgorithm()` can be simplified even more if the password is passed and will always user `UTF8.GetBytes()`

I could take this.

**Comment by anilswm** [comment]
Thanks @Fyers
