### ISSUE TITLE
Password hash encoding type 'hex' should be added separately

### ISSUE THREAD

**Issue by anilswm** [LoginRadius/csharp-password-hash#4]
We are providing these Encoding Types
 public enum **EncodingType**
    {
        Default = 0,
        Base64 = 1,
        UTF8 = 2
    }

For '**Default** ', we are converting password hash into a '**hex**' value. There should an explicit encoding type also for this. So we need to add one more type '**hex**'. The logic for '**Default**' will be the same.

**Comment by jz543fm** [comment]
Hi, what do you mean? Can you be more specific, thank you

**Comment by anilswm** [comment]
Hi @jz543fm , I have updated the description for this.
