### ISSUE TITLE
Add Pbkdf2 algo

### ISSUE THREAD

**Issue by anilswm** [LoginRadius/csharp-password-hash#5]

**Comment by DarthBenro008** [comment]
I would like to work on this issue, should the iterations of the hash function be standardised or should we enable the user to override the number of iterations?

**Comment by anilswm** [comment]
Hey @DarthBenro008 Yes, we should enable the user to override the number of iterations.

Thanks for contributing to LoginRadius Open Source.  As part of hacktoberfest, LoginRadius is also giving free swags and goodies to its contributors. Please check out our [Hacktoberfest Page](https://www.loginradius.com/engineering/page/hacktoberfest2020) and fill the form mentioned there to become eligible for free swags. :)
