### ISSUE TITLE
Add SHA512 algo

### ISSUE THREAD

**Issue by anilswm** [LoginRadius/csharp-password-hash#6]

**Comment by sahil9001** [comment]
@anilswm I want to take up this issue!

**Comment by anilswm** [comment]
Hey @sahil9001  Thanks for contributing to LoginRadius Open Source. As part of hacktoberfest, LoginRadius is also giving free swags and goodies to its contributors. Please check out our [Hacktoberfest Page](https://www.loginradius.com/engineering/page/hacktoberfest2020) and fill the form mentioned there to become eligible for free swags. :)

**Comment by sahil9001** [comment]
Thanks a lot! @anilswm It's been really fun resolving this issue!
